---
title: "Reconstructed Temperature of an Antractic Ice Core"
description: |
  Linear model showing fitted linear regression between temperature and line plot showing the reconstructed temperature of  an Antractic ice core using precipitation temperature (°C) δ18O (permil SMOW).
author:
  - name: Cali Pfleger
    url: {}
date: 02-03-2021
output:
  distill::distill_article:
    self_contained: false
    code_folding: true 
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(here)
library(readxl)
library(lubridate)
library(tidyr)
```

## Read in CSV 
```{r}
hw2 <- read_csv(here("data", "earth224.csv")) %>% # read in the data
  clean_names() #make the columns all lower case
```

## Linear Regression 
```{r}
d18ovsT_lm <- lm(precipitation_temperature ~d18o_permil, data = hw2) #linear regression 
#summary(d18ovsT_lm) 

#Linear Model Equation 
lm_eq <- function(hw2_df){

    m <- lm(precipitation_temperature ~d18o_permil, hw2_df);

    eq <- substitute((y) == a + b %.% (x)*","~~(r)^2~"="~r2, 

         list(a = format(unname(coef(m)[1]), digits = 2),

              b = format(unname(coef(m)[2]), digits = 2),

             r2 = format(summary(m)$r.squared, digits = 3)))

    as.character(as.expression(eq));

}
```

## Create Dataframe for Plotting
```{r}
#make the data a dateframe (not sure if needed)
hw2_df = as.data.frame(hw2)

iso_d18o <-data.frame(d18o_permil=hw2_df[,3]) #select the d18o for ice core 

#predict the confidence fit lower and upper bounds
temperature <- predict(d18ovsT_lm, newdata = iso_d18o, interval = "confidence")

temperature_se  <- predict(d18ovsT_lm, newdata = iso_d18o, se.fit = TRUE, interval = "confidence")

# read as dateframe so you can merge the two sheets together 
temp_df = as.data.frame(temperature)

temp_se_df = as.data.frame(temperature_se)

temp_se_lower  = temp_se_df$fit.lwr - temp_se_df$se.fit
temp_se_higher  = temp_se_df$fit.upr + temp_se_df$se.fit

temp_se_lower = as.data.frame(temp_se_lower)
temp_se_higher = as.data.frame(temp_se_higher)

#merged sheets
ice_core_temp <- cbind(hw2_df, temp_df, temp_se_lower, temp_se_higher)
```

## Plot the Linear Regression
```{r}
p <- ggplot(hw2_df, aes(x= d18o_permil, y= precipitation_temperature)) + 
  geom_point() +
  geom_smooth(method = "lm", formula = y ~ x) +
  theme_bw() +
    labs(title = "Relationship between Temperature and Perecipation",
     caption =  expression("Figure 1: Linear model showing fitted linear regression between Temperature (°C) \n and δ18O (permil SMOW)."),
     subtitle = "Cali Pfleger") +
        xlab(expression( ~"δ" ^{~"18"}~"O (permil SMOW)")) +
        ylab(expression(Temperature ~("°C"))) +
   theme(
     text = element_text( family = "serif", size = 18),
    plot.title = element_text(hjust = 1, size = 14, face = "bold"), # Center title position and size
    plot.subtitle = element_text(hjust = 0, size =13),
   plot.caption = element_text(hjust = 1, size = 10, vjust = -2.5)) 

confint(d18ovsT_lm, "d18o_permil", level = 0.95) #95% confidence interval for d18o 
confint(d18ovsT_lm, "(Intercept)", level = 0.95)


p1 <- p + geom_text(x = -30, y = 0, label = lm_eq(hw2_df), parse = TRUE) + geom_text(x = -29, y = -7, label = "n = 8")

p1

```


## Plot the Data! 
```{r}
ggplot(ice_core_temp, aes(x= mean_age_kr_bp, y= fit)) + #read in data and set x and y values
  geom_ribbon(aes(ymin= temp_se_lower, ymax= temp_se_higher), linetype= 2, alpha= 0.5, fill = "dodgerblue")  +
   geom_ribbon(aes(ymin= lwr, ymax= upr), linetype= 2, alpha= 0.5, fill = "cadetblue1")  +
  geom_line(color = "black", size = 0.1) + #plot the fit as a line
  geom_point(size= 0.5, color = "black") +
  theme_bw() +
    labs(title = "Antartic Ice Core Temperature Reconstruction",
     caption =  expression("Figure 2: Line plot showing the reconstructed temperature of  an Antractic ice core using precipitation temperature (°C) δ18O (permil SMOW).\n The black line shows the mean of the reconstruction trend, the dark blue shading shows the 68% confidence interval and the light blue shading shows the \n 95% confidence interval for the reconstruction."),
     subtitle = "Cali Pfleger") +
        xlab("Age (kyr BP)") +
        ylab(expression(Temperature ~("°C"))) +
   theme(
     text = element_text( family = "serif", size = 18),
    plot.title = element_text(hjust = 1, size = 18, face = "bold"), # Center title position and size
    plot.subtitle = element_text(hjust = 0, size =12),
   plot.caption = element_text(hjust = 1, size = 6, vjust = -5), 
  axis.ticks = element_line(size = 0)) + 
  scale_x_continuous(n.breaks = 12) 

```





